### ISSUE TITLE
RedCross Repeater @ Moos: License expired [KSR994]

### ISSUE THREAD

**Issue by mgenelins** [mgenelins/w0yc-repeaters#10]
The commercial License for the Colocated Minneapolis Red Cross Repeater at Moos has expired. Email attempts the last several months to get someone to make contact, dispatch or enter into any agreement have been unsuccessful.

FCC ULS Database shows [KSR994] as valid through 2030. 
- [ ] Ask for a newly printed official copy of the KSR994 license from Minneapolis Red Cross.

![fc669d8e-99b7-4259-ad8c-1caa78798c6e](https://user-images.githubusercontent.com/12549819/144652730-90ca7f86-38b1-471d-8d51-36e0614fc850.jpg)
![5fd2a18a-2412-47ef-b4bd-15e39d5fe59d](https://user-images.githubusercontent.com/12549819/144652737-9851bcd4-7f95-43a6-87ab-b3a792967249.jpg)

**Comment by mgenelins** [comment]
FCC ULS Database screen shot:

![Screen Shot 2021-12-03 at 12 17 29 PM](https://user-images.githubusercontent.com/12549819/144652973-7b44b7dd-c57e-442a-9ca6-84126cd7f78b.png)

**Comment by mgenelins** [comment]
Pic of repeater at Moos:
![babcb13c-6360-4074-b6c2-9360241df3b2](https://user-images.githubusercontent.com/12549819/144653047-5880acdf-a3d7-46c1-b274-d1d91aaedaa4.jpg)

**Comment by KD0TLS** [comment]
Wow, I’ve never really seen the famed Moos tower station. Does this licensing issue potentially leave an open slot at Moos? From: Matt GenelinSent: Friday, December 3, 2021 12:19 PMTo: mgenelins/w0yc-repeatersCc: SubscribedSubject: Re: [mgenelins/w0yc-repeaters] RedCross Repeater @ Moos: License expired [KSR994] (Issue #10) Pic of repeater at Moos:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mgenelins** [comment]
@KD0TLS Moos tower Unmasked! Ha! I forget that not everyone has visited the famed room 140 on the 19th floor. Yes, that's a sneak preview of what things look like. I should really post a full set of pictures of all the racks.

To answer the question of if a new antenna has opened up- not yet. The Minneapolis Red Cross insists that they are using this 'critical piece of infrastructure' yet nobody from the club has heard any traffic on their repeater. We've tried for months to setup a sked, to no availability.

So, I am advocating that we release this antenna from 453.xxx for other uses. I have been advocating via email with @Ben Franske that we simply repurpose the repeater as DMR and offer up a talk group to all non-profits on such a future system. It would make more sense, and make better use of the UHF commercial spectrum.

**Comment by mgenelins** [comment]
More email back and forth. RedCross states that system is off-air, cannot test correctly. Dan Peitso tried to schedule a weekday test, @mgenelins asked for a weekend test, PL tone and frequency. Never heard back.

This system is pending email comms from:
- [x] Someone from the RedCross that can provide an updated license.
- [x] Ben Franske to email @mgenelins a real, original, contact person to see if we can decomm the system. 

It's likely that this system was installed before the written agreements that Ben had created for Memorandum of Understandings that the club now uses. This may be a political issue in the future.

**Comment by mgenelins** [comment]
Ben emailed back in August 2022 Matt to approve decomissioning of this system and site removal.

System removed from Site during October 15 2022 visit. Sitting in Matt's garage.
