### ISSUE TITLE
Need to move 442.425 NH7CY/R West St. Paul to another frequency

### ISSUE THREAD

**Issue by mgenelins** [mgenelins/w0yc-repeaters#13]
Matt has received complains from P25 users of the St. Paul W0YC/R 442.425 repeater that they hear the shared-use frequency of NH7CY/R on the same channel from West. St. Paul. 

Perhaps we can move West St. Paul to the new Minneapolis/Moos Frequency closer to the center of the band? 
Or
Make use of an SNP pair for this DMR system?

**Comment by captainchemtrail** [comment]
I'm all for an SNP pair given the WSP site doesn't have a huge coverage area. 

Also, would like to grab the duplexer from Moos (maybe on the same day we grab the NXDN repeater). That way we can retune the new duplexer and swap it with the one on the WSP repeater with minimal downtime.
