### ISSUE TITLE
NH7CY/R having desense on SNP pair

### ISSUE THREAD

**Issue by captainchemtrail** [mgenelins/w0yc-repeaters#16]
NH7CY/R has desense on the new frequency. 

- Check duplexer tuning / connections
- 25/85 again?
- Other crap on frequency?

**Comment by captainchemtrail** [comment]
Also, C-Bridge familiarization for active TGs on new network.

**Comment by mgenelins** [comment]
Moved 442.425 to 444.725 SNP frequency with Jason and Bob during October 15, 2022 Site visit at Moos.
Closing this issue as resolved for now.

**Comment by captainchemtrail** [comment]
443.275 / 448.275 for the new pair.

**Comment by Deathn00dle** [comment]
done

**Comment by captainchemtrail** [comment]
done

**Comment by mgenelins** [comment]
I believe Jason moved this to 444.200 / 449.200 at Moos, rigfht?

**Comment by captainchemtrail** [comment]
Correct. 443.275 was not chosen for proximity to other transmitter. 

444.200/449.200 is the new pair.

**Comment by mgenelins** [comment]
Sweet! @Deathn00dle I have updated https://github.com/mgenelins/w0yc-repeaters/blob/main/README.md with the current frequency and status; great work on this issue; thanks for remembering to close it! yay!
