### ISSUE TITLE
Move 147.150 TX/RX duplexor from St. Paul to Moos

### ISSUE THREAD

**Issue by mgenelins** [mgenelins/w0yc-repeaters#28]
With Tristen's new Motorola Quantro repeater at 350 watts delivered Sunday September 17, 2023 to moos, we now need the duplexor from St. Paul campus moved and hooked up at Moos in Minneapolis.
Pickup St. Paul Duplexor.

- [x] Turn down 147.150 Kenwood Backup system on 114.8hz.
- [x] Update repeater book that backup system is off the air now.
- [x] Deliver and attach TX/RX duplexor to Moos.
- [x] Test new coverage of new 350 watt 147.150 W0YC/R.
- [x] Email Tristen and W0yc groups io list that it's ready to coverage test.
- [x] Update repeater book with new coverage details, PL tone and NAC 700 code - indicate new system and MIXED MODE.

**Comment by mgenelins** [comment]
Duplexor deliered; re-tune scheduled tomorrow with Ian and @Deathn00dle .

**Comment by BendixKingHam** [comment]
Duplexer re-tuned.

**Comment by mgenelins** [comment]
@BendixKingHam Nice work! I can't believe you made me type Bendix King Ham with my own fingers. 😸

**Comment by mgenelins** [comment]
@BendixKingHam, what are the follow-up todos for getting this repeater on the air? Do we need jumper cables ordered with appropriate (which appropriate) connectors on them?

**Comment by BendixKingHam** [comment]
Repeater is on air at this time, running on the old aprs dual band until we can find a more permanent solution

**Comment by BendixKingHam** [comment]
we'll still need to set up linking router etc. for now we'll leave it standalone till we can get input from Sean on plumbing it into the internet

**Comment by BendixKingHam** [comment]
147.15 is offline again, looks like the PA fail light wasn't erroneous, was hearing a whining sound under Morse id's.

**Comment by mgenelins** [comment]
New system installed; moving new system issues to issue #28 .
