### ISSUE TITLE
Ham Lake: Switch out 224.940 for 224.820 - New System Build

### ISSUE THREAD

**Issue by mgenelins** [mgenelins/w0yc-repeaters#6]
Ralph N0AWN and Matt N0YNT have a new Bridgecomm 222 MHz repeater in stock to replace the old 224.940. Matt has verified June 2021 that a low-coverage, coordinated, 224.94 exists and is on the air in Rosemount, MN. It's time to move 224.94 out of the metro to achieve coordination.

**Comment by mgenelins** [comment]
Another three hours in 10/23/2021 last night. Programming is from 147.210 W0BU/R from several years back. Going with newer version controller (2018, new cpu) of Arcomm RC 210 - version 7.611. Firmware upgrades don't seem to be straightforward, so skipping those to get this system out the door. Will have to learn how to upgrade firmware on older controller first.

Bridgecomm repeater seems to have fantom keyups that is not coming from the controller every few hours; about 750ms key-up for no reason. RF decks are completely under control of RC210 controller, yet RF decks indicate TX-up for 750ms, as if a signal was present on RX but no lights. Weird.

Controller programming continues; many errors were observed in the translation between v6.035 and v7.611 of the software. Different CPU generations and shitty programming software seem to be at fault.

- [x] Matt to reach out to Ralph for coordination paperwork for other systems on the site so Matt can get 224.820 paperwork started.

**Comment by mgenelins** [comment]
Scheduled for a site install on Saturday, December 4, 2021 at 1300 on-site in Ham Lake.

**Comment by mgenelins** [comment]
- [ ] Still need to complete coordination paperwork for a new system. 
- [x] Move Email thread to this issue to track coordination technical specifications.

**Comment by KD0TLS** [comment]
Thanks for the update! Unrelated, but I hope this brings the Ham Lake digipeater closer to reality.  Todd D.

**Comment by mgenelins** [comment]
@KD0TLS Not sure about the Ham Lake Digipeater? Can you tell me more on who was thinking that might be a thing?

**Comment by mgenelins** [comment]
Pending:
- [ ] Still need to complete coordination paperwork for a new system.
- [x] Audio level adjustment on 224.820 to bring UP Rx levels, and DOWN the beeps and ID levels.
- [x] Replace remote base with a Maxtrac that has proper audio and PL levels.

**Comment by KD0TLS** [comment]
You were telling me Ralph was doing that.

**Comment by mgenelins** [comment]
@KD0TLS Oh, okie. Not sure if I have any updates from Ralph on the digipeater topic. He hasn't mentioned anything memorable to me in awhile.

**Comment by mgenelins** [comment]
Ham Lake site visit today at 2pm CT 2-20-2022:

Replaced remote base with another broken Motorola GM300 radio; RX bad on ebay radio. Put old remote base radio back into service, re-tuned audio and TX. TX is drifting off-frequency, which causes RX to drift. 

- [ ] Need to replace Remote base radio entirely.

Disabled 180 sec. timeout by re-programming the BridgeComm repeater itself. 
- [ ] 30 Watts is max power on this system; voice IDs should match that, not 50 Watts. Need to fix.

Turned down the beep levels with the "tone" pot inside the RC210 controller. Voice IDs are too loud still; Dan N0KFB suggested that we disable all voice IDs. 
- [ ] Matt to re-program out those Voice ID's and re-visit on future date.

Ralph N0AWN suggested that we upgrade to a Motorola CDM 1550 or CDM 1550. 
- [x] Matt to acquire one from eBay and program and get ready for a future site visit.

RC210 V 7.611 controller does not seem to take full programming load. Spews an error when programming; likely software version mis-match. Controller likely needs a firmware upgrade to a version that we have software for. PC software is v 7.610, firmware on controller is v7.611.

- [ ] Matt to program up the old RC210 controller on V6.x.x as a hot spare in case this controller keeps giving us issues. Have on the ready for hot swap for Ralph.

**Comment by mgenelins** [comment]
Okie, this issue is getting stale. I am going to move the action items to individual issues and close this one as stale.
