### ISSUE TITLE
223.900 RPT RG142 Receiver coax ordered.

### ISSUE THREAD

**Issue by dfujikiv** [mgenelins/w0yc-repeaters#7]
Ordered one 2 foot long RG142 (double shielded) Type N  bulkhead to PL male connector. This replaces the two cables that went from the bulkhead to the ARR preamp and the attenuator to the receiver.

![image](https://user-images.githubusercontent.com/13591935/121241638-45997580-c861-11eb-910f-5f1f2ef74bb2.png)

Comment: The ID-O-Matic V4 controller audio was originally adjusted for the ARR preamp signal and antennutor, which have been removed due to possible failure of the preamp. It makes sense that the audio level may now be too low. The controller generated ID audio is now at least 3 db louder than the audio from the receiver.

**Comment by mgenelins** [comment]
Coax received. Matt to schedule site visit to install jumper.

**Comment by mgenelins** [comment]
Scheduled for install today, October 22, 2021.

**Comment by mgenelins** [comment]
@dfujikiv is there an easy way to adjust the receiver audio up as well? I can make a second trip to the site to do that this weekend, if you provide guidance on how to adjust the levels.

**Comment by dfujikiv** [comment]
Matt,
If you want to try adjusting audio, Here is the ID-O-Matic controller board
layout.

The "RECVR": pot is probably what needs to be tweaked:

[image: image.png]

**Comment by mgenelins** [comment]
Whoops! That image didn't make it and this issue is now closed. I have emailed @dfujikiv directly on a new, fresh, email thread so I can create a new issue for tracking.
