### ISSUE TITLE
Metro4: Coverage issues

### ISSUE THREAD

**Issue by mgenelins** [mgenelins/w0yc-repeaters#9]
Wow. I haven’t really been able to ker-chunk it for about two weeks. Last time I did, someone came on completely unreadable.

Usually, I can bring it up with an HT indoors (though not well enough to actually use it). Now, 25W into a Yagi doesn’t make it. I’ll need to check when I do a bit of driving into Minneapolis proper. Also, KA0RXU (Robert) in Roseville isn’t able to bring up the .650 and he’s not that far. I saw on your GitHub list that you had planned to replace the antenna so I assumed that was the issue. Not sure what’s going on, but glad to know it’s operational.

BTW, just had a brief chat with Tom (owner of the .725) and he was able to get into the .600 from 694 and E. River Rd with an HT (though somewhat broken). So, the new repeater is making it into southern Anoka County and I can ker-chunk it for a solid S3 in Anoka itself.

I’d be interested if you can reach it with a mobile from your area, or at least hear it.

 
Todd,

Ok cool- thanks for the report. I’ll add a GitHub issue to track this. It sounds like something is broken. 

The girls issues are more of a tracking todo list of things that may or may not be actively broken. The GMRS antenna, while dead, was elected not to be replace by Shane awhile back, so it’s on me to figure out a replacement. In the mean time it’s on a GP-9. 

I’ll have a poolside when I am feeling a bit better. Seem to have come down with a cold last night. 

-Matt

**Comment by mgenelins** [comment]
Hey Todd-

Great signal from Oakdale today on Metro 4. Was out with the doggie for a bit (felt a bit better). 

Not sure what’s happening to the north west.  I’ll keep tearing. 

-Matt
 
I set up the base station yesterday – 45W into a gain omni above roof level – and was just on the edge of ker-chunking Metro 4. Sometimes it did, other times it didn’t make it. I was full quieting into Terry’s UHF .050 repeater using the same setup. Weird.

Recall that I ordinarily can ker-chunk Metro 4 with an HT indoors.

Interested how Dave is hearing it. A guy in Roseville hasn’t been able to bring Metro 4 up either, and that’s pretty close. Tom in Fridley also couldn't bring it up.

 
Todd,

Weird. I wonder if something is in the way to the north and west of Metro 4. East metro coverage appears the same-same as usual. 

I drove by the site last weekend and noticed some window cleaning equipment hanging off the side near the antennas. I wonder if something antenna-wise got nocked around in the wind.

-matt

**Comment by mgenelins** [comment]
Site visit 10/22/2021 at 1300: SWR on system appears on MFJ Meter (suspect bad) as 1.5:1. Power output is 30-50 watts.

Observed as I drove to Greenfield, MN that Metro 4 drops to S2 faster then 443.000, which is similar equipment (Motorola Radius radios) on the same site. 

Likely that we need to get a replacement antenna for the higher band 462.650 instead of running a GMRS repeater on a amateur band antenna.

- [ ] Matt to order a commercial stick. Perhaps try home depot or Amazon? Single high-ish gain antenna, no joints for water protection.

**Comment by KD0TLS** [comment]
You received Metro 4 all the way out to Greenfield? I couldn't bring it up
in Robbinsdale this weekend while driving.

**Comment by mgenelins** [comment]
@KD0TLS Yes, S2 in Greenfield, MN.

**Comment by mgenelins** [comment]
Todd reports up/down issues. Matt has noticed the 'power fail/reboot' tones on the air recently.

This might be a power issue at the site.

**Comment by mgenelins** [comment]
Todd reports coverage issues continue; not able to bring up Metro 4 from Plymouth still.

**Comment by mgenelins** [comment]
These coverage issues seem to be antenna related; we are using a ham-split antenna on 462, which will be resolved with issue #4 . Closing this issue as duplicate.
